// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2024, 6:41:02 PM
const configMerger = require("C:/Users/sheida/Pictures/nejadd/my-nuxt-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/sheida/Pictures/nejadd/my-nuxt-app/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/layouts/**/*.{vue,js,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/pages/**/*.{vue,js,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/composables/**/*.{js,ts,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/utils/**/*.{js,ts,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/{A,a}pp.{vue,js,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/{E,e}rror.{vue,js,mjs}","C:/Users/sheida/Pictures/nejadd/my-nuxt-app/app.config.{js,ts,mjs}"] } }));

module.exports = config
